# Generated by Django 5.1.7 on 2025-04-02 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_api_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_new',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vacancy'),
        ),
    ]
